In [249]:
!pip install pyspark

import pandas as pd
import numpy as np

Requirement already satisfied: pyspark in /srv/conda/envs/notebook/lib/python3.7/site-packages (3.1.1)
Requirement already satisfied: py4j==0.10.9 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pyspark) (0.10.9)

In [279]:
#load the csv file into dataframe
df = pd.read_csv('housing-data.csv')[:-18]
df

,Suburb,Type,Price,Distance,Zipcode,#Bedroom,#Bathroom,#-Car Garage,Lot_size,Region_name,Property_count
0,Abbotsford,h,1165000.0,2.5,3067.0,3.0,2.0,0.0,92.0,Northern Metropolitan,4019.0
1,Abbotsford,h,1050000.0,2.5,3067.0,2.0,1.0,0.0,129.0,Northern Metropolitan,4019.0
2,Abbotsford,h,1465000.0,2.5,3067.0,3.0,2.0,0.0,134.0,Northern Metropolitan,4019.0
3,Abbotsford,h,911000.0,3.0,3067.0,2.0,1.0,0.0,141.0,Northern Metropolitan,4019.0
4,Abbotsford,h,1635000.0,3.0,3067.0,3.0,1.0,0.0,142.0,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...
11574,Yarraville,h,985500.0,7.0,3013.0,4.0,1.0,5.0,445.0,Western Metropolitan,6543.0
11575,Yarraville,h,725000.0,7.0,3013.0,3.0,1.0,5.0,558.0,Western Metropolitan,6543.0
11576,Yarraville,h,1240000.0,6.3,3013.0,3.0,3.0,6.0,668.0,Western Metropolitan,6543.0
11577,Yarraville,h,1400000.0,6.3,3013.0,3.0,3.0,6.0,668.0,Western Metropolitan,6543.0
11578,Yarraville,h,1100000.0,6.3,3013.0,3.0,1.0,6.0,732.0,Western Metropolitan,6543.0

In [280]:
#checked for which column had null values and how many
df.isnull().sum()

Suburb            0
Type              0
Price             0
Distance          0
Zipcode           0
#Bedroom          0
#Bathroom         2
#-Car Garage      1
Lot_size          0
Region_name       0
Property_count    0
dtype: int64

In [281]:
#show rows with null values
df[df.isnull().any(axis=1)]

,Suburb,Type,Price,Distance,Zipcode,#Bedroom,#Bathroom,#-Car Garage,Lot_size,Region_name,Property_count
2844,Carnegie,h,1360000.0,11.4,3163.0,3.0,NaN,2.0,282.0,Southern Metropolitan,7822.0
9770,South Melbourne,h,980000.0,1.9,3205.0,2.0,1.0,NaN,64.0,Southern Metropolitan,5943.0
11335,Williamstown,h,2640000.0,8.0,3016.0,4.0,NaN,2.0,650.0,Western Metropolitan,6380.0

In [282]:
#replace all the zero values with NaN
df.replace(0,np.nan, inplace=True)

In [283]:
df

,Suburb,Type,Price,Distance,Zipcode,#Bedroom,#Bathroom,#-Car Garage,Lot_size,Region_name,Property_count
0,Abbotsford,h,1165000.0,2.5,3067.0,3.0,2.0,NaN,92.0,Northern Metropolitan,4019.0
1,Abbotsford,h,1050000.0,2.5,3067.0,2.0,1.0,NaN,129.0,Northern Metropolitan,4019.0
2,Abbotsford,h,1465000.0,2.5,3067.0,3.0,2.0,NaN,134.0,Northern Metropolitan,4019.0
3,Abbotsford,h,911000.0,3.0,3067.0,2.0,1.0,NaN,141.0,Northern Metropolitan,4019.0
4,Abbotsford,h,1635000.0,3.0,3067.0,3.0,1.0,NaN,142.0,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...
11574,Yarraville,h,985500.0,7.0,3013.0,4.0,1.0,5.0,445.0,Western Metropolitan,6543.0
11575,Yarraville,h,725000.0,7.0,3013.0,3.0,1.0,5.0,558.0,Western Metropolitan,6543.0
11576,Yarraville,h,1240000.0,6.3,3013.0,3.0,3.0,6.0,668.0,Western Metropolitan,6543.0
11577,Yarraville,h,1400000.0,6.3,3013.0,3.0,3.0,6.0,668.0,Western Metropolitan,6543.0
11578,Yarraville,h,1100000.0,6.3,3013.0,3.0,1.0,6.0,732.0,Western Metropolitan,6543.0

In [284]:
df.isnull().sum()

Suburb              0
Type                0
Price               0
Distance            1
Zipcode             0
#Bedroom           12
#Bathroom          18
#-Car Garage      891
Lot_size            1
Region_name         0
Property_count      0
dtype: int64

In [285]:
#gather all columns to replace NaN values except Car Garage column
cols = ['Suburb','Type','Price', 'Distance','Zipcode','#Bedroom','#Bathroom','Lot_size','Region_name','Property_count']

In [286]:
#Replaced all the columns which has null values with median since they are sorted by suburb already except the '#-Car Garage' column because it's possible for a house not to have garage
df[cols] = df[cols].fillna(df[cols].median())

In [287]:
df

,Suburb,Type,Price,Distance,Zipcode,#Bedroom,#Bathroom,#-Car Garage,Lot_size,Region_name,Property_count
0,Abbotsford,h,1165000.0,2.5,3067.0,3.0,2.0,NaN,92.0,Northern Metropolitan,4019.0
1,Abbotsford,h,1050000.0,2.5,3067.0,2.0,1.0,NaN,129.0,Northern Metropolitan,4019.0
2,Abbotsford,h,1465000.0,2.5,3067.0,3.0,2.0,NaN,134.0,Northern Metropolitan,4019.0
3,Abbotsford,h,911000.0,3.0,3067.0,2.0,1.0,NaN,141.0,Northern Metropolitan,4019.0
4,Abbotsford,h,1635000.0,3.0,3067.0,3.0,1.0,NaN,142.0,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...
11574,Yarraville,h,985500.0,7.0,3013.0,4.0,1.0,5.0,445.0,Western Metropolitan,6543.0
11575,Yarraville,h,725000.0,7.0,3013.0,3.0,1.0,5.0,558.0,Western Metropolitan,6543.0
11576,Yarraville,h,1240000.0,6.3,3013.0,3.0,3.0,6.0,668.0,Western Metropolitan,6543.0
11577,Yarraville,h,1400000.0,6.3,3013.0,3.0,3.0,6.0,668.0,Western Metropolitan,6543.0
11578,Yarraville,h,1100000.0,6.3,3013.0,3.0,1.0,6.0,732.0,Western Metropolitan,6543.0

In [288]:
#we check if there is still any null value. So we can see that we have  just one in car-garage left. we can handle that later
df.isnull().sum()

Suburb              0
Type                0
Price               0
Distance            0
Zipcode             0
#Bedroom            0
#Bathroom           0
#-Car Garage      891
Lot_size            0
Region_name         0
Property_count      0
dtype: int64

In [289]:
#replaced all the NaN with zero, because an apartment can have zero garage
df.replace(np.nan,0, inplace=True)

In [316]:
df

,Suburb,Type,Price,Distance,Zipcode,#Bedroom,#Bathroom,#-Car Garage,Lot_size,Region_name,Property_count
0,Abbotsford,h,1165000.0,2.5,3067.0,3.0,2.0,0.0,92.0,Northern Metropolitan,4019.0
1,Abbotsford,h,1050000.0,2.5,3067.0,2.0,1.0,0.0,129.0,Northern Metropolitan,4019.0
2,Abbotsford,h,1465000.0,2.5,3067.0,3.0,2.0,0.0,134.0,Northern Metropolitan,4019.0
3,Abbotsford,h,911000.0,3.0,3067.0,2.0,1.0,0.0,141.0,Northern Metropolitan,4019.0
4,Abbotsford,h,1635000.0,3.0,3067.0,3.0,1.0,0.0,142.0,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...
11574,Yarraville,h,985500.0,7.0,3013.0,4.0,1.0,5.0,445.0,Western Metropolitan,6543.0
11575,Yarraville,h,725000.0,7.0,3013.0,3.0,1.0,5.0,558.0,Western Metropolitan,6543.0
11576,Yarraville,h,1240000.0,6.3,3013.0,3.0,3.0,6.0,668.0,Western Metropolitan,6543.0
11577,Yarraville,h,1400000.0,6.3,3013.0,3.0,3.0,6.0,668.0,Western Metropolitan,6543.0
11578,Yarraville,h,1100000.0,6.3,3013.0,3.0,1.0,6.0,732.0,Western Metropolitan,6543.0

In [291]:
#Time to deal with negative impossible data (Bedroom,car Garage, Lot_size) e.g Bedroom can't have negative number of rooms
df[(df['#Bedroom']<0)]

,Suburb,Type,Price,Distance,Zipcode,#Bedroom,#Bathroom,#-Car Garage,Lot_size,Region_name,Property_count
3455,Craigieburn,h,600000.0,20.6,3064.0,-1.0,2.0,2.0,630.0,Northern Metropolitan,15510.0

In [292]:
df[(df['#-Car Garage']<0)]

,Suburb,Type,Price,Distance,Zipcode,#Bedroom,#Bathroom,#-Car Garage,Lot_size,Region_name,Property_count
4189,Essendon,h,1150000.0,7.5,3040.0,3.0,1.0,-5.0,658.0,Western Metropolitan,9264.0

In [293]:
df[(df['Lot_size']<0)]

,Suburb,Type,Price,Distance,Zipcode,#Bedroom,#Bathroom,#-Car Garage,Lot_size,Region_name,Property_count
5343,Hampton,h,2500000.0,13.8,3188.0,5.0,4.0,2.0,-100.0,Southern Metropolitan,5454.0

In [294]:
#here we handle the negative numbers in the 3 fields that contains negative values; Bedroom, Lot_size and Car Garage.
df['#Bedroom'] =df['#Bedroom'].mask(df['#Bedroom']<0,np.nan)
df['Lot_size'] =df['Lot_size'].mask(df['Lot_size']<0,np.nan)
df['#-Car Garage'] =df['#-Car Garage'].mask(df['#-Car Garage']<0,np.nan)

In [295]:
df[(df['Property_count']==15510)]

,Suburb,Type,Price,Distance,Zipcode,#Bedroom,#Bathroom,#-Car Garage,Lot_size,Region_name,Property_count
3420,Craigieburn,h,499000.0,20.6,3064.0,3.0,2.0,0.0,598.0,Northern Metropolitan,15510.0
3421,Craigieburn,h,595000.0,20.6,3064.0,4.0,1.0,0.0,641.0,Northern Metropolitan,15510.0
3422,Craigieburn,h,582500.0,20.6,3064.0,3.0,1.0,0.0,947.0,Northern Metropolitan,15510.0
3423,Craigieburn,t,310000.0,20.6,3064.0,2.0,1.0,1.0,38.0,Northern Metropolitan,15510.0
3424,Craigieburn,t,340000.0,20.6,3064.0,2.0,1.0,1.0,197.0,Northern Metropolitan,15510.0
3425,Craigieburn,h,412500.0,20.6,3064.0,3.0,2.0,1.0,197.0,Northern Metropolitan,15510.0
3426,Craigieburn,h,430000.0,20.6,3064.0,3.0,2.0,1.0,280.0,Northern Metropolitan,15510.0
3427,Craigieburn,h,475000.0,20.6,3064.0,4.0,2.0,1.0,294.0,Northern Metropolitan,15510.0
3428,Craigieburn,h,390000.0,20.6,3064.0,3.0,1.0,1.0,301.0,Northern Metropolitan,15510.0
3429,Craigieburn,h,365000.0,20.6,3064.0,3.0,1.0,1.0,320.0,Northern Metropolitan,15510.0
3430,Craigieburn,h,485000.0,20.6,3064.0,3.0,2.0,1.0,321.0,Northern Metropolitan,15510.0
3431,Craigieburn,h,510000.0,20.6,3064.0,4.0,2.0,1.0,336.0,Northern Metropolitan,15510.0
3432,Craigieburn,h,465000.0,20.6,3064.0,3.0,1.0,1.0,338.0,Northern Metropolitan,15510.0
3433,Craigieburn,t,420000.0,20.6,3064.0,3.0,2.0,2.0,219.0,Northern Metropolitan,15510.0
3434,Craigieburn,h,492000.0,20.6,3064.0,3.0,2.0,2.0,255.0,Northern Metropolitan,15510.0
3435,Craigieburn,h,425000.0,20.6,3064.0,3.0,2.0,2.0,263.0,Northern Metropolitan,15510.0
3436,Craigieburn,h,480000.0,20.6,3064.0,4.0,2.0,2.0,312.0,Northern Metropolitan,15510.0
3437,Craigieburn,h,510000.0,20.6,3064.0,3.0,2.0,2.0,350.0,Northern Metropolitan,15510.0
3438,Craigieburn,h,548000.0,20.6,3064.0,4.0,2.0,2.0,400.0,Northern Metropolitan,15510.0
3439,Craigieburn,h,505000.0,20.6,3064.0,4.0,2.0,2.0,406.0,Northern Metropolitan,15510.0
3440,Craigieburn,h,595000.0,20.6,3064.0,4.0,2.0,2.0,420.0,Northern Metropolitan,15510.0
3441,Craigieburn,h,667500.0,20.6,3064.0,4.0,2.0,2.0,448.0,Northern Metropolitan,15510.0
3442,Craigieburn,h,500000.0,20.6,3064.0,3.0,2.0,2.0,448.0,Northern Metropolitan,15510.0
3443,Craigieburn,h,592500.0,20.6,3064.0,4.0,2.0,2.0,448.0,Northern Metropolitan,15510.0
3444,Craigieburn,h,632000.0,20.6,3064.0,4.0,2.0,2.0,448.0,Northern Metropolitan,15510.0
3445,Craigieburn,h,552000.0,20.6,3064.0,3.0,2.0,2.0,448.0,Northern Metropolitan,15510.0
3446,Craigieburn,h,492000.0,20.6,3064.0,4.0,2.0,2.0,479.0,Northern Metropolitan,15510.0
3447,Craigieburn,h,667000.0,20.6,3064.0,4.0,2.0,2.0,480.0,Northern Metropolitan,15510.0
3448,Craigieburn,h,640000.0,20.6,3064.0,4.0,2.0,2.0,480.0,Northern Metropolitan,15510.0
3449,Craigieburn,h,565000.0,20.6,3064.0,4.0,2.0,2.0,482.0,Northern Metropolitan,15510.0
3450,Craigieburn,h,523000.0,20.6,3064.0,4.0,2.0,2.0,484.0,Northern Metropolitan,15510.0
3451,Craigieburn,h,515000.0,20.6,3064.0,3.0,2.0,2.0,490.0,Northern Metropolitan,15510.0
3452,Craigieburn,h,800000.0,20.6,3064.0,4.0,2.0,2.0,511.0,Northern Metropolitan,15510.0
3453,Craigieburn,h,590000.0,20.6,3064.0,4.0,2.0,2.0,512.0,Northern Metropolitan,15510.0
3454,Craigieburn,h,600000.0,20.6,3064.0,4.0,2.0,2.0,560.0,Northern Metropolitan,15510.0
3455,Craigieburn,h,600000.0,20.6,3064.0,NaN,2.0,2.0,630.0,Northern Metropolitan,15510.0
3456,Craigieburn,h,680000.0,20.6,3064.0,5.0,3.0,2.0,646.0,Northern Metropolitan,15510.0
3457,Craigieburn,h,607500.0,20.6,3064.0,3.0,2.0,2.0,654.0,Northern Metropolitan,15510.0
3458,Craigieburn,h,506000.0,20.6,3064.0,6.0,2.0,2.0,655.0,Northern Metropolitan,15510.0
3459,Craigieburn,h,1000000.0,20.6,3064.0,6.0,3.0,2.0,752.0,Northern Metropolitan,15510.0
3460,Craigieburn,h,665000.0,20.6,3064.0,4.0,2.0,2.0,756.0,Northern Metropolitan,15510.0
3461,Craigieburn,h,615000.0,20.6,3064.0,4.0,2.0,2.0,756.0,Northern Metropolitan,15510.0
3462,Craigieburn,h,735000.0,20.6,3064.0,4.0,2.0,2.0,771.0,Northern Metropolitan,15510.0
3463,Craigieburn,h,660000.0,20.6,3064.0,3.0,2.0,3.0,618.0,Northern Metropolitan,15510.0
3464,Craigieburn,h,725000.0,20.6,3064.0,4.0,2.0,3.0,854.0,Northern Metropolitan,15510.0
3465,Craigieburn,h,515500.0,20.6,3064.0,3.0,1.0,4.0,651.0,Northern Metropolitan,15510.0
3466,Craigieburn,h,716000.0,20.6,3064.0,3.0,2.0,6.0,1005.0,Northern Metropolitan,15510.0

In [300]:
#we use the bfill method to replace the NaN. The bfill uses the next valid observation to fill the gap nearest
df['#Bedroom'].fillna(method='bfill',inplace = True)
df['Lot_size'].fillna(method='bfill',inplace = True)
df['#-Car Garage'].fillna(method='bfill',inplace = True)

In [301]:
#checking the affected role to see if the NaN value has been reflected
df.loc[(df['Property_count']==15510) & (df['Lot_size']==630)]

,Suburb,Type,Price,Distance,Zipcode,#Bedroom,#Bathroom,#-Car Garage,Lot_size,Region_name,Property_count
3455,Craigieburn,h,600000.0,20.6,3064.0,5.0,2.0,2.0,630.0,Northern Metropolitan,15510.0

In [302]:
df.loc[(df['Property_count']==9264) & (df['Lot_size']==658)]

,Suburb,Type,Price,Distance,Zipcode,#Bedroom,#Bathroom,#-Car Garage,Lot_size,Region_name,Property_count
4189,Essendon,h,1150000.0,7.5,3040.0,3.0,1.0,2.0,658.0,Western Metropolitan,9264.0

In [322]:
df.loc[(df['Property_count']==5454) & (df['Price']==2500000.0)]

,Suburb,Type,Price,Distance,Zipcode,#Bedroom,#Bathroom,#-Car Garage,Lot_size,Region_name,Property_count
5343,Hampton,h,2500000.0,13.8,3188.0,5.0,4.0,2.0,630.0,Southern Metropolitan,5454.0
5354,Hampton,h,2500000.0,13.7,3188.0,4.0,3.0,2.0,684.0,Southern Metropolitan,5454.0
5394,Hampton,h,2500000.0,13.8,3188.0,4.0,2.0,4.0,683.0,Southern Metropolitan,5454.0

In [ ]:
#====================================Cosine Similarity================================================================================================

In [3]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import pandas as pd
import numpy as np

In [21]:
#took a slice of the whole dataset to train our model. It works with the large datasets as well
ddf = pd.read_csv('housing-data.csv')[:50]
ddf

,Suburb,Type,Price,Distance,Zipcode,#Bedroom,#Bathroom,#-Car Garage,Lot_size,Region_name,Property_count
0,Abbotsford,h,1165000.0,2.5,3067.0,3.0,2.0,0.0,92.0,Northern Metropolitan,4019.0
1,Abbotsford,h,1050000.0,2.5,3067.0,2.0,1.0,0.0,129.0,Northern Metropolitan,4019.0
2,Abbotsford,h,1465000.0,2.5,3067.0,3.0,2.0,0.0,134.0,Northern Metropolitan,4019.0
3,Abbotsford,h,911000.0,3.0,3067.0,2.0,1.0,0.0,141.0,Northern Metropolitan,4019.0
4,Abbotsford,h,1635000.0,3.0,3067.0,3.0,1.0,0.0,142.0,Northern Metropolitan,4019.0
5,Abbotsford,h,1315000.0,2.5,3067.0,2.0,1.0,0.0,147.0,Northern Metropolitan,4019.0
6,Abbotsford,h,1035000.0,2.5,3067.0,2.0,1.0,0.0,156.0,Northern Metropolitan,4019.0
7,Abbotsford,h,1180000.0,2.5,3067.0,2.0,1.0,0.0,162.0,Northern Metropolitan,4019.0
8,Abbotsford,h,941000.0,2.5,3067.0,2.0,1.0,0.0,181.0,Northern Metropolitan,4019.0
9,Abbotsford,h,1012500.0,2.5,3067.0,2.0,1.0,0.0,182.0,Northern Metropolitan,4019.0
10,Abbotsford,h,955000.0,2.5,3067.0,3.0,1.0,0.0,183.0,Northern Metropolitan,4019.0
11,Abbotsford,h,1000000.0,2.5,3067.0,3.0,1.0,0.0,198.0,Northern Metropolitan,4019.0
12,Abbotsford,h,1876000.0,2.5,3067.0,4.0,2.0,0.0,245.0,Northern Metropolitan,4019.0
13,Abbotsford,h,1375000.0,3.0,3067.0,3.0,1.0,0.0,299.0,Northern Metropolitan,4019.0
14,Abbotsford,h,940000.0,3.0,3067.0,2.0,1.0,0.0,424.0,Northern Metropolitan,4019.0
15,Abbotsford,h,855000.0,3.0,3067.0,3.0,2.0,1.0,92.0,Northern Metropolitan,4019.0
16,Abbotsford,h,850000.0,2.5,3067.0,3.0,2.0,1.0,94.0,Northern Metropolitan,4019.0
17,Abbotsford,h,1200000.0,2.5,3067.0,3.0,2.0,1.0,113.0,Northern Metropolitan,4019.0
18,Abbotsford,h,1195000.0,2.5,3067.0,3.0,2.0,1.0,120.0,Northern Metropolitan,4019.0
19,Abbotsford,h,1100000.0,2.5,3067.0,2.0,2.0,1.0,124.0,Northern Metropolitan,4019.0
20,Abbotsford,h,1176500.0,2.5,3067.0,2.0,1.0,1.0,138.0,Northern Metropolitan,4019.0
21,Abbotsford,h,1190000.0,3.0,3067.0,2.0,2.0,1.0,147.0,Northern Metropolitan,4019.0
22,Abbotsford,h,890000.0,2.5,3067.0,2.0,1.0,1.0,150.0,Northern Metropolitan,4019.0
23,Abbotsford,h,1447500.0,2.5,3067.0,3.0,3.0,1.0,166.0,Northern Metropolitan,4019.0
24,Abbotsford,h,1290000.0,2.5,3067.0,3.0,1.0,1.0,168.0,Northern Metropolitan,4019.0
25,Abbotsford,h,1030000.0,2.5,3067.0,2.0,1.0,1.0,172.0,Northern Metropolitan,4019.0
26,Abbotsford,h,1172500.0,2.5,3067.0,2.0,1.0,1.0,195.0,Northern Metropolitan,4019.0
27,Abbotsford,h,1480000.0,2.5,3067.0,2.0,1.0,1.0,202.0,Northern Metropolitan,4019.0
28,Abbotsford,h,1242000.0,2.5,3067.0,2.0,1.0,1.0,249.0,Northern Metropolitan,4019.0
29,Abbotsford,h,1402500.0,3.0,3067.0,3.0,1.0,1.0,270.0,Northern Metropolitan,4019.0
30,Abbotsford,u,480000.0,3.0,3067.0,2.0,1.0,1.0,601.0,Northern Metropolitan,4019.0
31,Abbotsford,u,550000.0,3.0,3067.0,2.0,1.0,1.0,1521.0,Northern Metropolitan,4019.0
32,Abbotsford,u,750000.0,3.0,3067.0,2.0,1.0,1.0,2379.0,Northern Metropolitan,4019.0
33,Abbotsford,h,1135000.0,2.5,3067.0,2.0,2.0,2.0,98.0,Northern Metropolitan,4019.0
34,Abbotsford,t,1525000.0,3.0,3067.0,4.0,2.0,2.0,102.0,Northern Metropolitan,4019.0
35,Abbotsford,h,1600000.0,2.5,3067.0,3.0,1.0,2.0,120.0,Northern Metropolitan,4019.0
36,Abbotsford,h,1290000.0,2.5,3067.0,3.0,2.0,2.0,147.0,Northern Metropolitan,4019.0
37,Abbotsford,h,1000000.0,3.0,3067.0,3.0,1.0,2.0,196.0,Northern Metropolitan,4019.0
38,Abbotsford,h,1350000.0,2.5,3067.0,3.0,2.0,2.0,214.0,Northern Metropolitan,4019.0
39,Abbotsford,h,1097000.0,2.5,3067.0,3.0,1.0,2.0,220.0,Northern Metropolitan,4019.0
40,Abbotsford,h,1310000.0,2.5,3067.0,2.0,1.0,2.0,238.0,Northern Metropolitan,4019.0
41,Abbotsford,h,1636000.0,2.5,3067.0,2.0,1.0,2.0,256.0,Northern Metropolitan,4019.0
42,Abbotsford,h,1330000.0,2.5,3067.0,4.0,2.0,2.0,780.0,Northern Metropolitan,4019.0
43,Abbotsford,u,1090000.0,2.5,3067.0,3.0,2.0,2.0,4290.0,Northern Metropolitan,4019.0
44,Aberfeldie,h,470000.0,9.1,3040.0,2.0,1.0,1.0,70.0,Western Metropolitan,1543.0
45,Aberfeldie,u,726000.0,9.1,3040.0,3.0,1.0,1.0,229.0,Western Metropolitan,1543.0
46,Aberfeldie,u,1160000.0,9.1,3040.0,3.0,2.0,1.0,309.0,Western Metropolitan,1543.0
47,Aberfeldie,h,760000.0,9.1,3040.0,3.0,1.0,1.0,321.0,Western Metropolitan,1543.0
48,Aberfeldie,h,840000.0,9.1,3040.0,2.0,1.0,1.0,373.0,Western Metropolitan,1543.0
49,Aberfeldie,h,1190000.0,9.1,3040.0,3.0,1.0,1.0,465.0,Western Metropolitan,1543.0

In [22]:
ddf.columns

Index(['Suburb', 'Type', 'Price', 'Distance', 'Zipcode', '#Bedroom',
       '#Bathroom', '#-Car Garage', 'Lot_size', 'Region_name',
       'Property_count'],
      dtype='object')

In [23]:
#since cosine similarity works only on non-strings/chars, I decided to get the fields with numerical values only
data = ddf[['Price','Distance','Zipcode','#Bedroom','#Bathroom','#-Car Garage','Lot_size','Property_count']]
data.sample(10)

,Price,Distance,Zipcode,#Bedroom,#Bathroom,#-Car Garage,Lot_size,Property_count
24,1290000.0,2.5,3067.0,3.0,1.0,1.0,168.0,4019.0
41,1636000.0,2.5,3067.0,2.0,1.0,2.0,256.0,4019.0
27,1480000.0,2.5,3067.0,2.0,1.0,1.0,202.0,4019.0
46,1160000.0,9.1,3040.0,3.0,2.0,1.0,309.0,1543.0
40,1310000.0,2.5,3067.0,2.0,1.0,2.0,238.0,4019.0
35,1600000.0,2.5,3067.0,3.0,1.0,2.0,120.0,4019.0
25,1030000.0,2.5,3067.0,2.0,1.0,1.0,172.0,4019.0
26,1172500.0,2.5,3067.0,2.0,1.0,1.0,195.0,4019.0
15,855000.0,3.0,3067.0,3.0,2.0,1.0,92.0,4019.0
1,1050000.0,2.5,3067.0,2.0,1.0,0.0,129.0,4019.0

In [24]:
cosine_similarity(data)

/srv/conda/envs/notebook/lib/python3.7/site-packages/sklearn/metrics/pairwise.py:56: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = np.float

array([[1.        , 0.99999989, 0.99999961, ..., 0.999998  , 0.99999815,
        0.99999763],
       [0.99999989, 1.        , 0.99999907, ..., 0.99999776, 0.99999772,
        0.99999669],
       [0.99999961, 0.99999907, 1.        , ..., 0.99999787, 0.99999836,
        0.9999988 ],
       ...,
       [0.999998  , 0.99999776, 0.99999787, ..., 1.        , 0.99999991,
        0.99999869],
       [0.99999815, 0.99999772, 0.99999836, ..., 0.99999991, 1.        ,
        0.99999929],
       [0.99999763, 0.99999669, 0.9999988 , ..., 0.99999869, 0.99999929,
        1.        ]])

In [25]:
#To get the similarity of the full dataset

# Preparing the categorigal data - encode labels with values between 0 and n number of categories in the column
label_enc = LabelEncoder()

In [26]:
result = ddf.apply(label_enc.fit_transform)

In [27]:
result.head()

,Suburb,Type,Price,Distance,Zipcode,#Bedroom,#Bathroom,#-Car Garage,Lot_size,Region_name,Property_count
0,0,0,24,0,1,1,1,0,1,0,1
1,0,0,18,0,1,0,0,0,8,0,1
2,0,0,40,0,1,1,1,0,9,0,1
3,0,0,10,1,1,0,0,0,11,0,1
4,0,0,44,1,1,1,0,0,12,0,1

In [28]:
#Using one hot encoder to fit our dataset
one_hot_enc = OneHotEncoder()

In [29]:
#one_hot_enc.fit(ddf)

/srv/conda/envs/notebook/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:395: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  check_array(X, dtype=np.int)

OneHotEncoder(categorical_features=None, categories=None, drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=True)

In [32]:
#fit and transform the dataset using one hot encoder
hot_enc= one_hot_enc.fit_transform(ddf).toarray()

/srv/conda/envs/notebook/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:110: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_int = np.zeros((n_samples, n_features), dtype=np.int)
/srv/conda/envs/notebook/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:111: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_mask = np.ones((n_samples, n_features), dtype=np.bool)

In [33]:
hot_enc

array([[1., 0., 1., ..., 0., 0., 1.],
       [1., 0., 1., ..., 0., 0., 1.],
       [1., 0., 1., ..., 0., 0., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 0.],
       [0., 1., 1., ..., 1., 1., 0.],
       [0., 1., 1., ..., 1., 1., 0.]])

In [34]:
enc_df =pd.DataFrame(one_hot_enc.fit_transform(ddf).toarray())

/srv/conda/envs/notebook/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:110: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_int = np.zeros((n_samples, n_features), dtype=np.int)
/srv/conda/envs/notebook/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:111: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_mask = np.ones((n_samples, n_features), dtype=np.bool)

In [35]:
#Join with original dataset to view the encoded version 
ddf = ddf.join(enc_df)
ddf

,Suburb,Type,Price,Distance,Zipcode,#Bedroom,#Bathroom,#-Car Garage,Lot_size,Region_name,...,106,107,108,109,110,111,112,113,114,115
0,Abbotsford,h,1165000.0,2.5,3067.0,3.0,2.0,0.0,92.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,Abbotsford,h,1050000.0,2.5,3067.0,2.0,1.0,0.0,129.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
2,Abbotsford,h,1465000.0,2.5,3067.0,3.0,2.0,0.0,134.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,Abbotsford,h,911000.0,3.0,3067.0,2.0,1.0,0.0,141.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
4,Abbotsford,h,1635000.0,3.0,3067.0,3.0,1.0,0.0,142.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
5,Abbotsford,h,1315000.0,2.5,3067.0,2.0,1.0,0.0,147.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
6,Abbotsford,h,1035000.0,2.5,3067.0,2.0,1.0,0.0,156.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
7,Abbotsford,h,1180000.0,2.5,3067.0,2.0,1.0,0.0,162.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
8,Abbotsford,h,941000.0,2.5,3067.0,2.0,1.0,0.0,181.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
9,Abbotsford,h,1012500.0,2.5,3067.0,2.0,1.0,0.0,182.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
10,Abbotsford,h,955000.0,2.5,3067.0,3.0,1.0,0.0,183.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
11,Abbotsford,h,1000000.0,2.5,3067.0,3.0,1.0,0.0,198.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
12,Abbotsford,h,1876000.0,2.5,3067.0,4.0,2.0,0.0,245.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
13,Abbotsford,h,1375000.0,3.0,3067.0,3.0,1.0,0.0,299.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
14,Abbotsford,h,940000.0,3.0,3067.0,2.0,1.0,0.0,424.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
15,Abbotsford,h,855000.0,3.0,3067.0,3.0,2.0,1.0,92.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
16,Abbotsford,h,850000.0,2.5,3067.0,3.0,2.0,1.0,94.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
17,Abbotsford,h,1200000.0,2.5,3067.0,3.0,2.0,1.0,113.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
18,Abbotsford,h,1195000.0,2.5,3067.0,3.0,2.0,1.0,120.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
19,Abbotsford,h,1100000.0,2.5,3067.0,2.0,2.0,1.0,124.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
20,Abbotsford,h,1176500.0,2.5,3067.0,2.0,1.0,1.0,138.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
21,Abbotsford,h,1190000.0,3.0,3067.0,2.0,2.0,1.0,147.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
22,Abbotsford,h,890000.0,2.5,3067.0,2.0,1.0,1.0,150.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
23,Abbotsford,h,1447500.0,2.5,3067.0,3.0,3.0,1.0,166.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
24,Abbotsford,h,1290000.0,2.5,3067.0,3.0,1.0,1.0,168.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
25,Abbotsford,h,1030000.0,2.5,3067.0,2.0,1.0,1.0,172.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
26,Abbotsford,h,1172500.0,2.5,3067.0,2.0,1.0,1.0,195.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
27,Abbotsford,h,1480000.0,2.5,3067.0,2.0,1.0,1.0,202.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
28,Abbotsford,h,1242000.0,2.5,3067.0,2.0,1.0,1.0,249.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
29,Abbotsford,h,1402500.0,3.0,3067.0,3.0,1.0,1.0,270.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
30,Abbotsford,u,480000.0,3.0,3067.0,2.0,1.0,1.0,601.0,Northern Metropolitan,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
31,Abbotsford,u,550000.0,3.0,3067.0,2.0,1.0,1.0,1521.0,Northern Metropolitan,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
32,Abbotsford,u,750000.0,3.0,3067.0,2.0,1.0,1.0,2379.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
33,Abbotsford,h,1135000.0,2.5,3067.0,2.0,2.0,2.0,98.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
34,Abbotsford,t,1525000.0,3.0,3067.0,4.0,2.0,2.0,102.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
35,Abbotsford,h,1600000.0,2.5,3067.0,3.0,1.0,2.0,120.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
36,Abbotsford,h,1290000.0,2.5,3067.0,3.0,2.0,2.0,147.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
37,Abbotsford,h,1000000.0,3.0,3067.0,3.0,1.0,2.0,196.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
38,Abbotsford,h,1350000.0,2.5,3067.0,3.0,2.0,2.0,214.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
39,Abbotsford,h,1097000.0,2.5,3067.0,3.0,1.0,2.0,220.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
40,Abbotsford,h,1310000.0,2.5,3067.0,2.0,1.0,2.0,238.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
41,Abbotsford,h,1636000.0,2.5,3067.0,2.0,1.0,2.0,256.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
42,Abbotsford,h,1330000.0,2.5,3067.0,4.0,2.0,2.0,780.0,Northern Metropolitan,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
43,Abbotsford,u,1090000.0,2.5,3067.0,3.0,2.0,2.0,4290.0,Northern Metropolitan,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
44,Aberfeldie,h,470000.0,9.1,3040.0,2.0,1.0,1.0,70.0,Western Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
45,Aberfeldie,u,726000.0,9.1,3040.0,3.0,1.0,1.0,229.0,Western Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
46,Aberfeldie,u,1160000.0,9.1,3040.0,3.0,2.0,1.0,309.0,Western Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
47,Aberfeldie,h,760000.0,9.1,3040.0,3.0,1.0,1.0,321.0,Western Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
48,Aberfeldie,h,840000.0,9.1,3040.0,2.0,1.0,1.0,373.0,Western Metropolitan,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
49,Aberfeldie,h,1190000.0,9.1,3040.0,3.0,1.0,1.0,465.0,Western Metropolitan,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [36]:
print(cosine_similarity(hot_enc))

[[1.         0.63636364 0.81818182 ... 0.18181818 0.09090909 0.18181818]
 [0.63636364 1.         0.63636364 ... 0.18181818 0.27272727 0.18181818]
 [0.81818182 0.63636364 1.         ... 0.18181818 0.09090909 0.18181818]
 ...
 [0.18181818 0.18181818 0.18181818 ... 1.         0.72727273 0.81818182]
 [0.09090909 0.27272727 0.09090909 ... 0.72727273 1.         0.72727273]
 [0.18181818 0.18181818 0.18181818 ... 0.81818182 0.72727273 1.        ]]

/srv/conda/envs/notebook/lib/python3.7/site-packages/sklearn/metrics/pairwise.py:56: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = np.float